setw -g mode-keys vi

set -g default-terminal "screen-256color"
set -as terminal-overrides ",alacritty*:Tc"
bind-key -n C-a send-prefix
bind C-s set-window-option synchronize-panes
bind-key    Up    select-pane -U
bind-key    Down  select-pane -D
bind-key    Left  select-pane -L
bind-key    Right select-pane -R

bind s choose-tree -Zs -O activity

# lazy.vim requirements
set-option -sg escape-time 10
set-option -g focus-events on

# opencode
set-option -g extended-keys on

# Select pane with mouse click
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e; send-keys -M'"

# Fix select to copy due to above
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line \; send-keys -X copy-pipe-and-cancel "pbcopy
